
name: Cleanup Preview Environments

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup Preview Environment
        env:
          PREVIEW_URL: "preview-${{ github.event.pull_request.number }}.aurora-video-synth.dev"
        run: |
          echo "Cleaning up preview environment at $PREVIEW_URL"
          # Add cleanup commands here

